const colors = {
  light: {
    text: "#0A0F0A",
    tint: "#1B5E20",
    background: "#F2F6F2",
    foreground: "#0A0F0A",
    card: "#FFFFFF",
    cardForeground: "#0A0F0A",
    primary: "#1B5E20",
    primaryForeground: "#FFFFFF",
    secondary: "#00AEEF",
    secondaryForeground: "#FFFFFF",
    accent: "#FFD600",
    accentForeground: "#0A0F0A",
    muted: "#E8F0E9",
    mutedForeground: "#6B7280",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#D1E4D2",
    input: "#D1E4D2",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceElevated: "#F8FBF8",
  },
  dark: {
    text: "#F0F4F0",
    tint: "#4CAF50",
    background: "#060D06",
    foreground: "#F0F4F0",
    card: "#0F1F0F",
    cardForeground: "#F0F4F0",
    primary: "#4CAF50",
    primaryForeground: "#FFFFFF",
    secondary: "#00AEEF",
    secondaryForeground: "#FFFFFF",
    accent: "#FFD600",
    accentForeground: "#0A0F0A",
    muted: "#152115",
    mutedForeground: "#9CA3AF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3A1E",
    input: "#1E3A1E",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    surface: "#0F1F0F",
    surfaceElevated: "#162416",
  },
  radius: 20,
  cardColors: {
    bk: "#1B5E20",
    momo: "#E65100",
    im: "#0D47A1",
    equity: "#7B1FA2",
    cogebanque: "#1A237E",
  },
};

export default colors;
